### ISSUE TITLE
Undefined method `acts_as_list' on Class when creating new banner

### ISSUE THREAD

**Issue by nijirija** [holli/advert_selector#8] opened 2015-03-11 02:30 UTC
Hello,

In banners/new I'm getting an "Undefined method `acts_as_list' for..." error, risen by line 9 at app/models/advert_selector/helper_item.rb

Already tried reinstalling simple_form.

I'm using rails 4.1.8 and ruby 2.1.5 and looks like creating new placements works fine

Can you give me a hand please?

**Comment by holli** [comment] 2015-03-11 22:41
Hmm, I don't think its simple form related. More like acts_as_list related https://github.com/swanandp/acts_as_list . If you figure out it let me know or make a pull request to fix that.

**Comment by meltingice** [comment] 2015-05-13 18:23
+1 I'm getting the same thing. Using Rails 4.2.0 and Ruby 2.2.1.

**Comment by meltingice** [comment] 2015-05-13 18:31
The problem is that you're requiring things via the `Gemfile`, which does not happen when released as a gem. You need to explicitly require the dependencies in your library. I'll send a PR.

**Closed** 2015-05-14 18:15 UTC

**Comment by holli** [comment] 2015-05-14 18:39
Good point. Thanks for the PR. There is now a new version of the gem where this is fixed.
